### ISSUE TITLE
Alfred 4 Support

### ISSUE THREAD

**Issue by 3llomi** [ognistik/alfred-pasteflow#1]
Is there any chance I can get this working on Alfred 4?

**Comment by ognistik** [comment]
Unfortunately many aspects of the configuration are not compatible. I'm also about to release a big update that allows rich text, images, and files and I don't think some of that is compatible as well (since some of it relies on new automation tasks). Would be too much work trying to figure out what does work or what needs workarounds, so I don't think I'll do this sorry!
